### ISSUE TITLE
Feedback on splash page for CL

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cl.github.io#11]
1. It's awesome! Thank you so much @shawntanzk and @hkir-dev ! What follows are minor points, and I'm well aware that you're focusing on the big picture first. So thank you in advance for bearing with my comments.
2. Could you please increase the font size of anything other than the section titles? 
3. "The Cell Ontology (CL) is an OBO Foundry ontology covering the domain of canonical, natural biological cell types." => canonical, natural biological feels a little redundant. How about "...domain of natural cell types" or "physiological" or "physiologically-occurring". Possibly "The Cell Ontology (CL) is an OBO Foundry ontology covering the domain of physiological animal cell types.". Yes there are a few non-metazoan cell types in there, but the focus is on Metazoa.  
4. The funders' icons are apparently hyperlinked, but the redirect seems inactive.
5. "Browse The Cell Ontology - powered by the Ontology Lookup Service (OLS)" should probably read "...powered by the EMBL-EBI's Ontology...". True, EBI is acknowledged on the page, but it's a generic acknowledgement. Mention of OLS in the Ontology Tools Integrated section should also quote EMBL-EBI. 
6. In the FAIR principles section, Gene ontology should read Gene Ontology please. 
7. The GO FAIR screenshot and all others are not legible or linkable - are they meant to be?
8. Could the phrasing in the Active Community section be improved please. 
9. cell ontology should read Cell Ontology (Widely Compatible and Applications sections)
10. Links under Applications (e.g. BICCN, HubMap) and Contact Us (e.g. GitHub) open in the same page. Personally I'd prefer it if they opened in new pages.

Thank you!

**Comment by shawntanzk** [comment]
> Could you please increase the font size of anything other than the section titles?

- [ ] should be able to, will look into this. To fix

> "The Cell Ontology (CL) is an OBO Foundry ontology covering the domain of canonical, natural biological cell types." => canonical, natural biological feels a little redundant. How about "...domain of natural cell types" or "physiological" or "physiologically-occurring". Possibly "The Cell Ontology (CL) is an OBO Foundry ontology covering the domain of physiological animal cell types.". Yes there are a few non-metazoan cell types in there, but the focus is on Metazoa.

- [ ] I took this from @addiehl 2016 paper - would want his input before changing this. 

> The funders' icons are apparently hyperlinked, but the redirect seems inactive.

- [ ] to fix, ideally removing hyper link capability (don't think its needed)

> "Browse The Cell Ontology - powered by the Ontology Lookup Service (OLS)" should probably read "...powered by the EMBL-EBI's Ontology...". True, EBI is acknowledged on the page, but it's a generic acknowledgement. Mention of OLS in the Ontology Tools Integrated section should also quote EMBL-EBI.

- [x] to fix

> In the FAIR principles section, Gene ontology should read Gene Ontology please.

- [x] to fix

> The GO FAIR screenshot and all others are not legible or linkable - are they meant to be?

- Defs not linkable, I prefer it not to be fully legible as that's not the point - it's just eye candy more than anything. 

> Could the phrasing in the Active Community section be improved please.

- [ ] will try lol, not sure if I can >.<

> cell ontology should read Cell Ontology (Widely Compatible and Applications sections)

@matentzn pointed this out too - fixed now

> Links under Applications (e.g. BICCN, HubMap) and Contact Us (e.g. GitHub) open in the same page. Personally I'd prefer it if they opened in new pages.

- [x] to fix

**Comment by shawntanzk** [comment]
moved to https://github.com/cell-ontology/cell-ontology.github.io/issues/6
