### ISSUE TITLE
Improve "Download" button

### ISSUE THREAD

**Issue by lubianat** [obophenotype/cl.github.io#3]
It could be interesting to have a "Download" section with links to different file formats (i.e. OWL and JSON)

**Comment by shawntanzk** [comment]
easily add-able, but honestly, id rather redirect to our github for all other file formats - if CL decides to change the release products, for example, don't want broken links.

**Comment by lubianat** [comment]
@shawntanzk  agreed ; equally possible. Maybe then indicate to users sure it is an .OWL file ? smt like: 
![image](https://user-images.githubusercontent.com/7917951/170745906-ee31b582-de30-4675-9c9e-ae7658471d6a.png)

already would be a bit clearer
