### ISSUE TITLE
Make ontology browsable from the website (e.g. embed OLS)

### ISSUE THREAD

**Issue by lubianat** [obophenotype/cl.github.io#4]
Maybe it is possible to directly embed OLS using an <iframe>; that would be a better usability than warping the user to OLS.

**Comment by shawntanzk** [comment]
there is a tree viewer widget, but I can't rmbr exactly why, but we decided on autocomplete widget, but I think we can potentially look in adding the tree viewer widget (in addition) down the road

**Comment by shawntanzk** [comment]
closing this, if we still would like to consider tree viewer, happy to open another ticket in https://github.com/cell-ontology/cell-ontology.github.io/issues
