### ISSUE TITLE
Add SPARQL Query interface for browsing the ontology

### ISSUE THREAD

**Issue by lubianat** [obophenotype/cl.github.io#5]
That might take a while, but it would be interesting to enable SPARQL queries on CL from the browser. 

The following steps would be needed: 
* Setting up an SPARQL Endpoint for CL (https://triplydb.com/ is the simplest and cheapest way to do it that I am aware of)

* Setting up Sparnatural Visual Query Builder (example at https://sparnatural.eu/demos/demo-bnf/index.html?lang=en), a client-side Javascript app for building visual SPARQL queries. It is slightly more user friendly than implementing just an SPARQL UI. 

I've done both things in the recent past and might help in that direction.

**Comment by balhoff** [comment]
You could point to [Ubergraph](https://github.com/INCATools/ubergraph): https://api.triplydb.com/s/DgAXeV5Pc

**Comment by lubianat** [comment]
Thanks @balhoff, it looks like a good option! Setting up the Sparnatural query builder on top of it should not be too hard. I'll play around with that in the near future

**Comment by lubianat** [comment]
Classes in CL do not seem to have `rdf:type` relations, though, and the visual builder kind of counts on that. Maybe the endpoint for this application will need some tweaking of the ontology, perhaps adding an ad-hoc metaclass for "cell type"

**Comment by matentzn** [comment]
@lubianat Not sure what you mean - `rdf:type` relation? The only `rdf:type` relation a class would ever have is "owl:Class", i.e. https://api.triplydb.com/s/hA5OLTEib

Or do you mean something else? Superclasses perhaps? i.e. https://api.triplydb.com/s/UP_rSc6RM

**Comment by shawntanzk** [comment]
moved to https://github.com/cell-ontology/cell-ontology.github.io/issues/7
