### ISSUE TITLE
Fix transparency issues in the session with examples of integration

### ISSUE THREAD

**Issue by lubianat** [obophenotype/cl.github.io#6]
It would be good if logos for CZI and GO were displayed with white background
![image](https://user-images.githubusercontent.com/7917951/170744099-c952505e-850a-48fd-bd89-467dc47e169e.png)

**Comment by shawntanzk** [comment]
LOL this was a lucky thing, those are png, and i was considering making BICCN one transparent too, but glad to know that white background is preferable - easy fix, will do sometime next week

**Comment by shawntanzk** [comment]
Fixed
