### ISSUE TITLE
Move this whole thing to a new organisation

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cl.github.io#9]
@hkir-dev would you mind doing this please? 
I think best to just clone this to a new organisation as mentioned by Chris? 
If we can get this on cell-ontology.github.io that would be amazing
We can keep this repo until we have addressed all the issues before closing.

**Comment by hkir-dev** [comment]
New repo: https://github.com/cell-ontology/cell-ontology.github.io 
And the new site published: https://cell-ontology.github.io/
Keeping this repo for the possible issues. We can delete afterwards.
